/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rhz_game_JniCall */

#ifndef _Included_com_rhz_game_JniCall
#define _Included_com_rhz_game_JniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rhz_game_JniCall
 * Method:    callCMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_rhz_game_JniCall_callCMethod
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
